### PR TITLE
Bump DGS-Codegen => 5.6.9

### PR DESCRIPTION
**Pull request by zorglube**

### CODE REVIEW

**Comment by Ernir** [comment]
Is it possible to merge this PR to bring the plugin into sync with the DGS project, or does something need to happen first? Anything a happy user can help with? :)

**Comment by zorglube** [comment]
I'd would tell you it will arrive soon, but it depend on @deweyjose .

**Comment by Ernir** [comment]
> I'd would tell you it will arrive soon, but it depend on @deweyjose .

All righty, I take it that means we're waiting on @deweyjose to chime in to merge & release. :)

Any clarity on when/whether we expect to see upgrades again would be kindly appreciated.

**Comment by zorglube** [comment]
> > I'd would tell you it will arrive soon, but it depend on @deweyjose .
> 
> All righty, I take it that means we're waiting on @deweyjose to chime in to merge & release. :)
> 
> Any clarity on when/whether we expect to see upgrades again would be kindly appreciated.

Sorry I can't tell you, I don't know @deweyjose enough to have any clue on the merge delay. 

Sometimes it had took 10 minutes, some time it has took months. 

If you really need the update, you can fork the project and build the "release" you need.

**Comment by deweyjose** [comment]
> Is it possible to merge this PR to bring the plugin into sync with the DGS project, or does something need to happen first? Anything a happy user can help with? :)

Hi @Ernir I'll take a look at this PR today. Was there a particular bug fix between DGS codegen 5.6.3 and 5.6.9 that was blocking you from using this plugin?

**Comment by Ernir** [comment]
> Sorry I can't tell you, I don't know @deweyjose enough to have any clue on the merge delay.
> 
> Sometimes it had took 10 minutes, some time it has took months.
> 
> If you really need the update, you can download the sources and build the "release" you need -- literally it's an, edit sources then `mvn install` --

No worries, I was hoping for the tag to grab the attention of @deweyjose , and looks like that worked! I realize you couldn't answer this yourself. :) 

> Hi @Ernir I'll take a look at this PR today. Was there a particular bug fix between DGS codegen 5.6.3 and 5.6.9 that was blocking you from using this plugin?

Thanks!

There is no bug fix that I was looking for, but I was aware of https://github.com/Netflix/dgs-codegen/pull/497 which introduced what looks like a nice new feature.

I have continued to use this plugin, this feature being missing was not blocking. Happy to see I can continue to do so, thanks for the maintenance work!

**Comment by deweyjose** [comment]
Ok good to know @Ernir. I did merge this PR but unfortunately there is more work than simply bumping the DGS version.

@zorglube any chance you could run `mvn install` locally prior to submitting PRs? I'll working on fixing `main`. Also for now we need to bump the plugin version in pom.xml for now.

**Comment by deweyjose** [comment]
@Ernir version 1.29 of this plugin has been released.

**Comment by Ernir** [comment]
> @Ernir version 1.29 of this plugin has been released.
> 
> #67

Fantastic, thanks a lot!

**Comment by zorglube** [comment]
> Ok good to know @Ernir. I did merge this PR but unfortunately there is more work than simply bumping the DGS version.
> 
> @zorglube any chance you could run `mvn install` locally prior to submitting PRs? I'll working on fixing `main`. Also for now we need to bump the plugin version in pom.xml for now.

Sorry ! I probably messed up with all the branchs I have into my repo.

**Pull request merged**
