### PR TITLE
Support specifying language directly instead of relying on class being on classpath

### LINKED ISSUE #5: Please support <language>KOTLIN</language>

### PR DESCRIPTION
**Pull request by AlexRiedler**
I believe this resolves #5

### CODE REVIEW

**Comment by michaeldlfx** [comment]
@deweyjose Hey! Thanks for the maven port.

Any hope that we can merge this PR soon?

**Comment by deweyjose** [comment]
I will take care of it this am.

**Comment by deweyjose** [comment]
@michaeldlfx @AlexRiedler  this has been merged and released. 1.10 should be available now.

**Comment by michaeldlfx** [comment]
@deweyjose brilliant, thank you! 
This is a major improvement 🎉

**Pull request merged**
