### PR TITLE
IIEA10527  Made code changes to reflect the netflix changes. May need…

### PR DESCRIPTION
**Pull request by lakshmisunid**
As part of Netflix dgs codegen [v5.3.0](https://github.com/Netflix/dgs-codegen/releases/tag/v5.3.0), 3 new configurations have been created. Have added those here to provide maven compatibility.

Co-authored-by: Lakshmi Vijayachandran <lakshmi_vijayachandran@intuit.com>

### CODE REVIEW

**Review by anshuls1208 — APPROVED** [review]
lgtm. @lakshmisunid pls do add the references (or link to release version) for this review to go through. Thanks!

**Comment by deweyjose** [comment]
Hi thanks for the PR! Could you also bump the plug-in version in the Pom file to 1.23. We are working on automating.

I'll pull this and test tonight.

**Comment by lakshmisunid** [comment]
@deweyjose Thanks for looking into it. i have updated the plugin version as suggested.

**Comment by lakshmisunid** [comment]
@anshuls1208 I have added the link

**Comment by deweyjose** [comment]
Hi - did some local testing with @zorglube recent change (almost identical to this) and it looks like maven plugins have difficulty with nested maps. The includeEnumImports option will not deserialize properly.

I'm working on fixing this and adding addition entries in the docs for the new options.

**Comment by deweyjose** [comment]
Fixed in https://github.com/deweyjose/graphqlcodegen/pull/53 for future reference. Thanks again for the contributes @zorglube  @lakshmisunid and @anshuls1208. 

This repo needs better testing, it would have surfaced this issue ealier.

**Comment by lakshmisunid** [comment]
@deweyjose Thank you for the quick fix and adding the configurations

**Pull request closed without merging**
