### PR TITLE
Upgrade DSG-CodeGen 5.0.6 and Bump Java & libs & plugins versions

### PR DESCRIPTION
**Pull request by zorglube**

### CODE REVIEW

**Comment by zorglube** [comment]
By the way, mabe you'll prefere to keep `Java` to `JDK-8`.

**Comment by zorglube** [comment]
> By the way, mabe you'll prefere to keep `Java` to `JDK-8`.

Rolledback to `JDK-8`

**Comment by zorglube** [comment]
@deweyjose did you had a look on my PR ?

**Comment by kptfh** [comment]
@zorglube  please remove changes related to formatting of indents so we can see actual changes

**Comment by zorglube** [comment]
> @zorglube please remove changes related to formatting of indents so we can see actual changes

Maybe you can use se "split view + hide white space" : https://github.com/deweyjose/graphqlcodegen/pull/9/files?diff=split&w=1

**Pull request merged**
