### PR TITLE
Bump graphql-dgs-codegen-core => 5.5.0

### PR DESCRIPTION
**Pull request by lakshmisunid**
Updated to latest Dgs codegen release version of [5.5.0](https://github.com/Netflix/dgs-codegen/releases/tag/v5.5.0) 
Updated Readme to include addDeprecatedAnnotation

### CODE REVIEW

**Comment by lakshmisunid** [comment]
@deweyjose Could you please take a look?

**Comment by lakshmisunid** [comment]
@deweyjose Could you please help with updating the netflix dgs codegen version to the latest?

**Comment by deweyjose** [comment]
Hi, will take care of this tonight. Thanks for the PR!

**Comment by lakshmisunid** [comment]
@deweyjose Thank you for merging the branch. Can you let me know if this is released? I am not able to find the version 1.25.

**Comment by deweyjose** [comment]
Apologies - it's releasing now. It should be available shortly.

**Comment by lakshmisunid** [comment]
@deweyjose Thank you

**Pull request merged**
